# Generated by Django 5.0.2 on 2024-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logintohome", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
