# Generated by Django 5.0.2 on 2024-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_offer",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category_offer",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product_offer",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product_offer",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
