# Generated by Django 5.0.2 on 2024-03-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_coupen', '0002_rename_limit_coupons_quantity_coupons_min_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='name',
            new_name='title',
        ),
    ]
