# Generated by Django 5.0.2 on 2024-03-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_cart", "0006_delete_wishlist"),
        ("manage_coupen", "0003_rename_name_coupons_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manage_coupen.coupons",
            ),
        ),
    ]
