# Generated by Django 5.0.2 on 2024-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_cart", "0007_checkout_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="coupon_active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
