# Generated by Django 5.0.2 on 2024-03-05 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_alter_wallet_user_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet_user",
            name="balance",
        ),
    ]
