# Generated by Django 5.0.1 on 2024-02-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_category", "0002_category_description_alter_category_name"),
        ("manage_product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("img1", models.ImageField(upload_to="images/")),
                ("img2", models.ImageField(upload_to="images/")),
                ("img3", models.ImageField(upload_to="images/")),
                ("img4", models.ImageField(upload_to="images/")),
                ("is_listed", models.BooleanField(default=True)),
                ("original_price", models.IntegerField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage_category.category",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
