# Generated by Django 5.0.1 on 2024-02-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_product", "0002_products_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="products",
            name="img3",
        ),
        migrations.RemoveField(
            model_name="products",
            name="img4",
        ),
        migrations.RemoveField(
            model_name="products",
            name="original_price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="price",
        ),
        migrations.AddField(
            model_name="products",
            name="orginal_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="img1",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
