# Generated by Django 5.0.1 on 2024-02-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0005_products_img2_products_img3_products_img4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='orginal_price',
            new_name='original_price',
        ),
    ]
