# Generated by Django 5.0.1 on 2024-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_product", "0010_alter_products_img1_alter_products_img2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="img1",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img2",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img3",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img4",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
