# Generated by Django 5.0.2 on 2024-02-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0013_alter_variant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
    ]
