# Generated by Django 5.0.2 on 2024-03-05 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_product", "0017_variant_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="active",
            new_name="is_listed",
        ),
    ]
