# Generated by Django 5.0.1 on 2024-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
