# Generated by Django 5.0.1 on 2024-02-05 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_category", "0002_category_description_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
