# Generated by Django 5.0.1 on 2024-02-08 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_category", "0004_subcategory"),
        ("manage_product", "0006_rename_orginal_price_products_original_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Brand",
        ),
    ]
