# Generated by Django 5.0.1 on 2024-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_category", "0006_rename_subcategory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
