# Generated by Django 5.0.2 on 2024-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_category', '0007_category_is_listed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
